gui:
  showIcons: true
  nerdFontsVersion: 3
  showRandomTip: false
  expandFocusedSidePanel: true
  filterMode: fuzzy
  splitDiff: always
  timeFormat: "2006-01-02 15:04"
  shortTimeFormat: "15:04"
  border: rounded
  theme:
    activeBorderColor:
      - green
    inactiveBorderColor:
      - cyan
    searchingActiveBorderColor:
      - yellow
      - bold
    optionsTextColor:
      - default
    selectedLineBgColor:
      - default
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - blue
    cherryPickedCommitBgColor:
      - cyan
    markedBaseCommitFgColor:
      - blue
    markedBaseCommitBgColor:
      - yellow
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
git:
  pagers:
    - colorArg: always
      pager: "delta --dark --paging=never"
  commit:
    autoWrapCommitMessage: false
    autoWrapWidth: 72
  log:
    showGraph: always
    showWholeGraph: true
  ignoreWhitespaceInDiffView: true
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=format:'%C(auto)%h%d %s %C(white)%cr %C(cyan)%an'"
  allBranchesLogCmds:
    - "git log --graph --all --color=always --abbrev-commit --decorate --date=relative --pretty=format:'%C(auto)%h%d %s %C(white)%cr %C(cyan)%an'"
refresher:
  refreshInterval: 5
  fetchInterval: 120
update:
  method: background
confirmOnQuit: false
promptToReturnFromSubprocess: false
notARepository: quit
